#!/bin/bash
subcommands=(
"help"
"update"
)
function help() {
    echo subcommands
    for i in "${subcommands[@]}" ; do
        echo ">${i}"
    done
    for i in ls "cmd" ; do
      echo ">${i}"
    done
}

CMD=""
SUB=()
for i  ; do
    if [ "${CMD}" = "" ]; then
      if [ "${i:0:1}" = "-" ]; then
        continue
      fi
      CMD="${i}"
      continue
    else
      SUB+=("${i}")
    fi

done

case "${CMD}" in
  "help")
    help
    exit 0;;
  "update")
    if [ -d ./.git ]; then
      mv ./synconf ./synconf.old
      cp ./synconf.old ./synconf
      git fetch
      git merge
    else
      rm -rf ./*
      git clone https://github.com/kigawa8390/synconf.git --bare --progress ./
    fi
    exit 0;;
  *)
    if [ ! -f "cmd/${CMD}" ]; then
      help
      exit 1
    fi
    "cmd/${CMD}" "${SUB[@]}"
    exit 0;;
esac