#!/bin/bash
subcommands=(
  "synconf"
)
opt=(

)
function help() {
  echo subcommands
  for i in "${subcommands[@]}"; do
    echo "> ${i}"
  done
  for i in ls "cmd"; do
    echo "> ${i}"
  done
  echo options
  for i in "${opt[@]}"; do
    echo "> ${i}"
  done
}
function getCMD() {
  CMD=""
  SUB=()
  OPT=()
  for i; do
    if [ "${CMD}" = "" ]; then
      if [ "${i:0:1}" = "-" ]; then
        OPT+=("${i}")
        continue
      fi
      CMD="${i}"
      continue
    else
      SUB+=("${i}")
    fi
  done
}
function checkOpt() {
  for i in "${OPT[@]}"; do
    if bin/array contain "${i}" "${opt[@]}"; then
      continue
    else
      help
      echo "${i} opt is not exist"
      exit 1
    fi
  done
}
function setting() {
  DIR="${1}"
  bin/depend install "${DIR}/depend.conf"
  bin/configs set "${DIR}/configs.conf"

}

getCMD "${@}"
checkOpt

case "${CMD}" in
"synconf")
  setting "."
  ;;

esac
